name: SlimeE
version: 1.0
main: io.github.thecyberquake.slimee.SlimeE
api-version: 1.19
softdepend:
  - Slimefun
  - Galactifun
permissions:
  slimee.admin:
    description: Allows access to /se
  slimee.bypass:
    description: Can open/interact with EMC objects owned by other players