name: SlimeE
version: ${project.version}
main: io.github.thecyberquake.slimee.SlimeE
author: TheCyberQuake
description: Bring EE features into Slimefun
website: https://github.com/TheCyberQuake/SlimeE
api-version: 1.14
softdepend:
  - Galactifun
depend:
  - Slimefun
permissions:
  slimee.admin:
    description: Allows access to /se
  slimee.bypass:
    description: Can open/interact with EMC objects owned by other players